update script: use sshpass, support ip command

diff --git a/factory-user-data b/factory-user-data
--- a/factory-user-data
+++ b/factory-user-data
@@ -43,6 +43,18 @@ function show_usage {
     exit 1
 }
 
+function requirements {
+    if ! command -v git > /dev/null; then
+        echo "this script requires 'git' command"
+        exit 1
+    fi
+
+    if ! command -v sshpass > /dev/null; then
+        echo "this script requires 'sshpass' command"
+        exit 1
+    fi
+}
+
 function git_me {
     git $@
     if [[ $? != 0 ]]; then
@@ -55,12 +67,20 @@ function git_me {
 
 function wait_mod {
     while true; do
-        BROADCAST_IP=$(ifconfig | grep -oE "192\.168\.(50|51)\.255")
-        if [[ -z ${BROADCAST_IP} ]]; then
+        if command -v ifconfig > /dev/null; then
+            MOD_IP=$(ifconfig | grep -oE "192\.168\.(50|51)\.")
+        elif command -v ip > /dev/null; then
+            MOD_IP=$(ip route | grep -oE "192\.168\.(50|51)\." | head -1)
+        else
+            echo "command 'ifconfig' or 'ip' is required"
+            exit 1
+        fi
+
+        if [[ -z ${MOD_IP} ]]; then
             echo "Waiting MOD connection"
             sleep 1
         else
-            MOD_IP="${BROADCAST_IP::-3}1"
+            MOD_IP="${MOD_IP}1"
             break
         fi
     done
@@ -74,29 +94,19 @@ function copy_key {
         return 0
     fi
 
-    # checking access using mod_access_key and mod_early_users_key
-    for KEY_FILE in ~/.ssh/mod_access_key.pem ~/.ssh/mod_early_users_key.pem; do
-        ssh -o "PasswordAuthentication no" -i ${KEY_FILE} root@${MOD_IP} "touch /dev/null" 2>/dev/null
-        if [[ $? == 0 ]]; then
-            scp -i ${KEY_FILE} ~/.ssh/id_rsa.pub root@${MOD_IP}:/tmp/user-key 1>/dev/null 2>/dev/null
-            ssh -i ${KEY_FILE} root@${MOD_IP} "cat /tmp/user-key >> /root/.ssh/authorized_keys" 2>/dev/null
-            return 0
-        fi
-    done
-
-    ssh-copy-id root@${MOD_IP} 2>/dev/null
+    ssh-copy-id root@${MOD_IP}
 }
 
 function retrieve {
     echo "retrieving user data from MOD"
     for d in ${TO_COPY[@]}; do
-        scp -r root@${MOD_IP}:/root/$d $1/
-        ssh root@${MOD_IP} "cp -rf /root/$d /tmp/ && rm -rf /root/$d"
-        ssh root@${MOD_IP} "mv /root/user-data-backup/$d /root"
+        sshpass -p mod scp -r root@${MOD_IP}:/root/$d $1/
+        sshpass -p mod ssh root@${MOD_IP} "cp -rf /root/$d /tmp/ && rm -rf /root/$d"
+        sshpass -p mod ssh root@${MOD_IP} "mv /root/user-data-backup/$d /root"
     done
 
     # restart services
-    ssh root@${MOD_IP} "systemctl restart jack2 mod-host mod-ui"
+    sshpass -p mod ssh root@${MOD_IP} "systemctl restart jack2 mod-ui"
 
     echo "committing changes"
     git commit -a -m "factory user data updated by $(git config user.name)"
@@ -112,16 +122,18 @@ function deploy {
     echo "downloading the latest user data from remote repository"
     git_me pull --rebase
 
-    ssh root@${MOD_IP} "mkdir -p /root/user-data-backup"
+    sshpass -p mod ssh root@${MOD_IP} "mkdir -p /root/user-data-backup"
 
     echo "deploying user data to MOD"
     for d in ${TO_COPY[@]}; do
-        ssh root@${MOD_IP} "mv /root/$d /root/user-data-backup"
-        scp -r "$1/$d" root@${MOD_IP}:/root/
+        sshpass -p mod ssh root@${MOD_IP} "mv /root/$d /root/user-data-backup"
+        sshpass -p mod scp -r "$1/$d" root@${MOD_IP}:/root/
     done
 
+    sshpass -p mod ssh root@${MOD_IP} "sync"
+
     echo "restarting services"
-    ssh root@${MOD_IP} "systemctl restart jack2 mod-host mod-ui"
+    sshpass -p mod ssh root@${MOD_IP} "systemctl restart jack2 mod-ui"
 
     echo "done"
 }
@@ -133,7 +145,8 @@ if [[ "$#" != "2" ]] ||
     show_usage
 fi
 
+requirements
 wait_mod
-copy_key
 
+# execute action
 eval $2 $1
